# Generated by Django 6.0.4 on 2026-06-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('wifi', models.BooleanField(default=False)),
                ('power_socket', models.BooleanField(default=False)),
                ('coffee_price', models.CharField(max_length=20)),
            ],
        ),
    ]
