# Generated by Django 6.0.4 on 2026-06-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0002_cafe_air_conditioning_cafe_closing_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='air_conditioning',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='opening_time',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='outdoor_seating',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='pet_friendly',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='website',
        ),
    ]
